theme: jekyll-theme-minimal
title: zeyadmohamed20160-star's homepage
description: this is and ipa signer to sign ipas you must enter your details apple details so you can create a mobileprovison and a p12 file that are unieq and cannot get revoked and sign any ipa!!
